### PR TITLE
Use name instead of ID in switchOutputWorkflow Action

### PR DESCRIPTION
**Pull request by jheimbach**
| Q             | A
| ------------- | ---
| Branch?       | dev-master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #...   

The current implementation with referencing output workflows by ID in the conditional logic action breaks on export/import the form definition. 

I fixed this by referencing the output workflow by name instead.

### CODE REVIEW

**Comment by solverat** [comment]
Hey @jheimbach, thanks for your efforts. I'm not sure if we really should add this to PX. Is it something you need on PX installations, or could we move it to v5 (master branch)?

**Comment by jheimbach** [comment]
Hey @solverat,
we can merge that in v5. 

do i have to change the target branch?

**Comment by jheimbach** [comment]
@solverat will do.

btw. found out that the condition "outputworkflow" has the same problem, will fix it there also.

**Comment by solverat** [comment]
@jheimbach btw, if you have too many issues while rebasing to the latest master - don't hesitate to create new PR instead!

**Comment by solverat** [comment]
hey @jheimbach any updates on this?

**Comment by solverat** [comment]
@jheimbach I've just updated your PR:
- rebase to latest master
- also check for conditions "outputWorkflow" and change to name relation
- added a constraint check: if a given output workflow is required by any conditional logic, it is not allowed to change the ow's name, since it heavily depended on that now!

**Comment by solverat** [comment]
Thanks @jheimbach!

**Pull request merged**
