### PR TITLE
Pimcore X and PHP8.0 compatibility

### PR DESCRIPTION
**Pull request by dpfaffenbauer**

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
I cannot fix the test thing, since they depend on another repository of you...

**Comment by dpfaffenbauer** [comment]
@solverat ?

**Comment by jeykodev** [comment]
@dpfaffenbauer Thank you for the PR! Would be great if @solverat could check it. :)

**Comment by smaier** [comment]
@solverat  pleeeeease

**Pull request closed without merging**
