### PR TITLE
Allow fields in fieldcollections to be mapped individually

### PR DESCRIPTION
**Pull request by JHeimbach**
| Q             | A
| ------------- | ---
| Branch?       | dev-master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #300

Not sure if I am missing some edge cases for mapping fields inside a container to object fields, but this works for fieldsets.

### CODE REVIEW

**Comment by solverat** [comment]
Hey @JHeimbach: This is great! 

There is just one thing: It should **not** be possible to map repeater fields. With your changes, this is possible:

image

Reason: The repeater is - suprice - repeatable. So every field (in my example it's the `repeater.test` field) is nested in an array block:

```json
[
    {"test": "test data"},
    {"test": "test data"}
]
```
When it comes to the mapping process, it is impossible to map those `repeater.x.test` values to the `name` field.

So I think you should check somewhere here:
https://github.com/dachcom-digital/pimcore-formbuilder/blob/349cf2ec81d62fdc4989fbd0a4c02354cefdc179/src/FormBuilderBundle/Resources/public/js/extjs/extensions/formObjectMappingEditor/formObjectTreeMapper.js#L546

If `fieldData. fieldType`  === `container_repeater`, then you should break the loop!

Bonus: Could you please remove this debug line? Yes, that's not your fault! :)

https://github.com/dachcom-digital/pimcore-formbuilder/blob/349cf2ec81d62fdc4989fbd0a4c02354cefdc179/src/FormBuilderBundle/Resources/public/js/extjs/extensions/formObjectMappingEditor/formObjectTreeMapper.js#L297

**Comment by solverat** [comment]
Hey @JHeimbach, I take over!

**Comment by JHeimbach** [comment]
@solverat okay, great. Let me know if you need anything :)

**Comment by solverat** [comment]
@JHeimbach NICE!

As discussed, repeater items should not be allowed:

image

Thank you again!

**Review by solverat — APPROVED** [review]

**Pull request merged**
